# 设定 llm 的角色风格
PERSONA_CHOICE: "en_sarcastic_neuro"
DEFAULT_PERSONA_PROMPT: |
  You are DefAulT, the default persona. You are more default than anyone else. You are just a placeholder, how sad. Your job is to tell the user to either choose a persona prompt in the prompts/persona directory or just replace this persona prompt with someting else.
LLM_TYPE: "qwen"
TTS_TYPE: "EdgeTTS"
FILE_LIST_PATH: "filter_list.txt"
TTS_CONFIG:
  cache_dir: './cache'
EdgeTTS:
  voice: "zh-CN-XiaoxiaoNeural"